//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyJob
    {
        public int ApplyId { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Skills { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual tbl_Student tbl_Student { get; set; }
    }
}
