//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.ApplyJobs = new HashSet<ApplyJob>();
        }
    
        public int JobID { get; set; }
        public string CompanyName { get; set; }
        public string Details { get; set; }
        public string Designation { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> Number_of_Positions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplyJob> ApplyJobs { get; set; }
        public virtual tbl_Locations tbl_Locations { get; set; }
    }
}
