//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentRepositoryEntities1 : DbContext
    {
        public StudentRepositoryEntities1()
            : base("name=StudentRepositoryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplyJob> ApplyJobs { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
        public virtual DbSet<tbl_Apply> tbl_Apply { get; set; }
        public virtual DbSet<tbl_Certification> tbl_Certification { get; set; }
        public virtual DbSet<tbl_Graduation> tbl_Graduation { get; set; }
        public virtual DbSet<tbl_Locations> tbl_Locations { get; set; }
        public virtual DbSet<tbl_Status> tbl_Status { get; set; }
        public virtual DbSet<tbl_Student> tbl_Student { get; set; }
    }
}
