//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Admin
    {
        public int AdminID { get; set; }
       
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Contact { get; set; }
        //[RegularExpression("([A-Za-z])+( [A-Za-z]+)", ErrorMessage = "Username Should be alphabets only.")]
        [Required]
        [StringLength(10, MinimumLength = 5)]
        [Display(Name = "User name")]
        [RegularExpression(@"(\S\D)+", ErrorMessage = " Space and numbers not allowed")]

        public string Username { get; set; }
        [RegularExpression(@"^(?=(.*[a-z]){1,})(?=(.*[\d]){1,})(?=(.*[\W]){1,})(?!.*\s).{7,30}$",
                 ErrorMessage = "Password must have one Special character and 1 numeric and 1 uppercase and must have min 8 characters long")]

        public string Password { get; set; }
        public string Email { get; set; }
    }
}
