//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Apply
    {
        public int ApplyId { get; set; }
        public Nullable<int> CertificationID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Comments { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual tbl_Certification tbl_Certification { get; set; }
        public virtual tbl_Status tbl_Status { get; set; }
        public virtual tbl_Student tbl_Student { get; set; }
    }
}
